In [1]:
import sys
sys.path.append('../')

from common_imports import *
from common_functions import *

Merging each year into one data frame

In [2]:
dir_path = "weather_data/Cities/Salinas"
df = merge_files(dir_path)
df.sort_values(by='datetime').head(5)

,name,datetime,tempmax,tempmin,temp,feelslikemax,feelslikemin,feelslike,dew,humidity,...,solarenergy,uvindex,severerisk,sunrise,sunset,moonphase,conditions,description,icon,stations
0,"Salinas, California",2013-04-01,17.8,12.0,14.3,17.8,12.0,14.3,10.6,79.6,...,21.9,8,NaN,2013-04-01T06:51:57,2013-04-01T19:29:16,0.69,"Rain, Partially cloudy",Partly cloudy throughout the day with rain cle...,rain,"72593023233,74505823277,KMRY,KSNS,72491523259"
1,"Salinas, California",2013-04-02,17.7,9.8,12.7,17.7,9.6,12.7,9.6,82.5,...,23.6,9,NaN,2013-04-02T06:50:30,2013-04-02T19:30:08,0.75,"Rain, Partially cloudy",Clearing in the afternoon with morning rain.,rain,"72593023233,74505823277,KMRY,KSNS,72491523259"
2,"Salinas, California",2013-04-03,23.7,9.0,12.7,23.7,7.2,12.4,9.5,83.2,...,21.0,9,NaN,2013-04-03T06:49:03,2013-04-03T19:31:00,0.76,Partially cloudy,Clearing in the afternoon.,partly-cloudy-day,"72593023233,74505823277,KMRY,KSNS,72491523259"
3,"Salinas, California",2013-04-04,18.8,10.8,13.7,18.8,10.8,13.7,11.1,84.7,...,13.7,5,NaN,2013-04-04T06:47:37,2013-04-04T19:31:52,0.80,"Rain, Overcast",Cloudy skies throughout the day with rain clea...,rain,"72593023233,74505823277,KMRY,KSNS,72491523259"
4,"Salinas, California",2013-04-05,18.1,12.9,14.8,18.1,12.9,14.8,10.4,76.4,...,21.6,8,NaN,2013-04-05T06:46:10,2013-04-05T19:32:44,0.84,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,"72593023233,74505823277,KMRY,KSNS,72491523259"

In [3]:
df['name'] = 'Salinas, CA'

In [4]:
df.to_csv("weather_data/Merged_City/SalinasMerged.csv", index = False)

Merge wildfire incident with weather data